config/routes.rb
Rails.application.routes.draw do
  resources :trails, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gear.rb
class Gear < ApplicationRecord
    has_many :trail_gears
    has_many :trails, through: :trail_gears

end

app/models/trail.rb
class Trail < ApplicationRecord
    has_many :trail_gears
    has_many :gear, through: :trail_gears

    enum difficulty: [:easy, :moderate, :hard]

    def difficulty=(difficulty)
        write_attribute("difficulty", difficulty.to_i)
    end

    def gear=(gear)
        self.gear << Gear.find_or_initialize_by(title: gear[:title])
    end
end

app/models/trail_gear.rb
class TrailGear < ApplicationRecord
    belongs_to :trail
    belongs_to :gear
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController

    def index
        @trails = Trail.all
    end

    def new
        @gear = Gear.all
    end

    def create
        @trail = Trail.new(trail_params)
        if @trail.save
            redirect_to trails_path
        else
            render :new
        end
    end

    private

    def trail_params
        params.require(:trail).permit(:title, :description, :image_url, :length, :difficulty, gear_ids: [], gear: [:title])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hike</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trails/index.html.erb
<%= link_to "Add Trail", new_trail_path %>
<% @trails.each do |trail| %>
    <div style="width: 350px; border: solid 1px black; padding: 16px; margin: 16px;">
        <h2><%= trail.title %> | difficulty: <%= trail.difficulty %></h2>
        <p><%= trail.description %></p>
        <img style="width: 250px;" src="<%= trail.image_url %>" />
        <% if trail.gear.count > 0 %>
            <p>Hiking Gear Needed:</p>
            <ol>
                <% trail.gear.each do |gear| %>
                    <li><%= gear.title %></li>
                <% end %>
            </ol>
        <% end %>
    </div>
<% end %>

app/views/trails/new.html.erb
<form action="/trails" method="POST">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
    <div>
        <label for="trail_title">Title</label>
        <div>
            <input type="text" name="trail[title]" placeholder="title" />
        </div>
    </div>
     <div>
        <label for="trail_description">Description</label>
        <div>
            <textarea name="trail[description]" placeholder="description"></textarea>
        </div>
    </div>
     <div>
        <label for="trail_image_url">Image URL</label>
        <div>
            <input type="text" name="trail[image_url]" placeholder="image url" />
        </div>
    </div>
     <div>
        <label for="trail_length">Length</label>
        <div>
            <input type="text" name="trail[length]" placeholder="length" />
        </div>
    </div>
    <div>
        <label for="trail_difficulty">Difficulty</label>
        <div>
            <select name="trail[difficulty]"> <!--Supplement an id here instead of using 'name'-->
                <% Trail.difficulties.each do |key, value| %>
                    <option value="<%= value %>"><%= key %></option>
                <% end %>
            </select>
        </div>
    </div>
    <div>
        <label for="trail_gear">Hiking Gear:</label>
        <div>
            <% @gear.each do |gear| %>
                <label for="trail_gear"><%= gear.title %></label>
                <input type="checkbox" value="<%= gear.id %>" name="trail[gear_ids][]" />
            <% end %>
        </div>
    </div>
    <div>
        <label for="trail_gear_title">Create New Gear:</label>
        <div>
            <input type="text" name="trail[gear][title]" />
        </div>
    </div>
    <div>
        <button type="submit">Create</button>
    </div>
</form>